services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  NITSAN\NsHeadlessBlog\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  NITSAN\NsHeadlessBlog\Controller\BlogController:
    public: true
    tags: [ 'backend.controller' ]
